sudo: false
language: cpp

os:
  - linux
  - osx

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - zip
      - libgtk2.0-0
      - libx11-dev
      - libxkbfile-dev

before_install:
  - git submodule update --init --recursive
  - git clone --depth 1 https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 6.6.0
  - nvm use 6.6.0
  - npm config set python `which python`
  - npm install -g gulp
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - ./scripts/npm.sh install

script:
  - gulp hygiene --silent
  - gulp electron --silent
  - gulp compile --silent --max_old_space_size=4096
  - gulp optimize-vscode --silent --max_old_space_size=4096
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/test.sh --coverage; else ./scripts/test.sh; fi
  - ./scripts/test-integration.sh

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then node_modules/.bin/coveralls < .build/coverage/lcov.info; fi
