sudo: false
language: cpp

os:
  - linux
  - osx

env:
  - VSCODE_BUILD_VERBOSE=true

notifications:
  email: false
  slack:
    secure: "E0jH6mRCdrbjZwRCIE16xSKjCOPsTurm9DTqGu7ulhye8vQsy69iqxW2986pnTbcg4P5GXIeu19n6LxLeMBdVYCbQ/rPaznaZvgiJHTkJZOWidCUtuTIirUnuUNDkRQEfedq57Db6Bpo5nBxXH7LAiV+ofbP5YcTP0XRD1KMSrS5uuelWBUZk3KBYTCujwlXJWcn2tH9C5e3s2fehGq41prXUHvmn/sojXTi3ErQeLcjq7Io/ZiSZWPxgf77wuCWAp88j3Yp53TBVeyFepUQBWPh8yc9hXHqSO951ly4HnbC47GJCu41TbJouU8+If1NxgWIVHAGca9wGNUU0RsqY3prL+pPOZ/ab8bi71SdROVjAgsXYiRfGW3P63rmSw91Y3b2OYwLdzcPexL9Uh/lPsXdTY557oegntyr1YpPrlmREw2JmjVF6tzwZz6LLN/8eshowkheMVJUIyV4olhtP6F6gBI8zRZ52NrQQsKCOKPycwY33d91PexZIr8WeBdgUgJQbLrpfrshTx3GtRjTgqJObtBCleQhMfq/ja5xf2a6i+fdlyLDbSBJpYZAgo/uFQ2zV3Xm9rXOm7S4JKKa6bMTo3OVrQ4GLc7Za1m1eVRsACXPkXKb2CycER3FFWxdMSRcQcItpiJLYflZXM3Elfu49NNw6mOz/7JI4SSG/BY="

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - zip
      - libgtk2.0-0

before_install:
  - git submodule update --init --recursive
  - git clone https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 5.10
  - nvm use 5.10
  - npm config set python `which python`
  - npm install -g gulp
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - ./scripts/npm.sh install

script:
  - gulp hygiene
  - gulp electron
  - gulp compile
  - gulp optimize-vscode
  - ./scripts/test.sh
  - ./scripts/test-integration.sh
