name: Info-Needed Closer
on:
  schedule:
    - cron: 20 12 * * * # 5:20am Redmond
  repository_dispatch:
    types: [trigger-needs-more-info]
  workflow_dispatch:

permissions:
  issues: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v5
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          path: ./actions
          persist-credentials: false
          ref: stable
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run info-needed Closer
        uses: ./actions/needs-more-info-closer
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          label: info-needed
          closeDays: 30
          closeComment: "Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on, then we will be happy to re-open this issue to pick up where we left off. \n\nHappy Coding!"
          pingDays: 30
          pingComment: "Hey @${assignee}, this issue might need further attention.\n\n@${author}, you can help us out by closing this issue if the problem no longer exists, or adding more information."
