version: 2.1
jobs:
  armorcode-validate:
    docker:
      - image: byrnedo/alpine-curl
    environment:
      product: Rishabh
      subProduct: circle_ci
      environment: Production
      token: $ARMORCODE_TOKEN
      buildTool: CIRCLE_CI
      buildNumber: "<< pipeline.number >>"
      end: 30
    steps:
      - run:
          name: "Armorcode Validate"
          command: |
              token=$ARMORCODE_TOKEN
              wget https://preprod.armorcode.ai/static/scripts/slastatus.sh
              sh slastatus.sh  
workflows:
  armorcode-validation-workflow:
    jobs:
      - armorcode-validate
