name: CopyCat
on:
  issues:
    types: [opened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'JacksonKearl/vscode-triage-github-actions'
          ref: v2
      - name: Run CopyCat (JacksonKearl/testissues)
        uses: ./copycat
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          owner: JacksonKearl
          repo: testissues
      - name: Run CopyCat (chrmarti/testissues)
        uses: ./copycat
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          owner: chrmarti
          repo: testissues
