name: "Deep Classifier: Assign Monitor"
on:
  issues:
    types: [assigned]

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'triage-needed') }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode-github-triage-actions"
          ref: stable
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: "Run Classifier: Monitor"
        uses: ./actions/classifier-deep/monitor
        with:
          botName: VSCodeTriageBot
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
