name: English Please
on:
  issues:
    types: [edited]

# also make changes in ./on-label.yml and ./on-open.yml
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        if: contains(github.event.issue.labels.*.name, '*english-please')
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: v40
          path: ./actions
      - name: Install Actions
        if: contains(github.event.issue.labels.*.name, '*english-please')
        run: npm install --production --prefix ./actions
      - name: Run English Please
        if: contains(github.event.issue.labels.*.name, '*english-please')
        uses: ./actions/english-please
        with:
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          cognitiveServicesAPIKey: ${{secrets.AZURE_TEXT_TRANSLATOR_KEY}}
          nonEnglishLabel: "*english-please"
          needsMoreInfoLabel: "needs more info"
          translatorRequestedLabelPrefix: "translation-required-"
          translatorRequestedLabelColor: "c29cff"
