valid inputs are ['token', 'storageKey']
2
Run ./actions/latest-release-monitor
4
/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:118
     if any error: fix error for better performance
    at Object.getInput (/home/runner/work/vscode/vscode/actions/node_modules/@actions/core/lib/core.js:118:15)
    at getRequiredInput (/home/runner/work/vscode/vscode/actions/common/utils.js:15:41)
    at Object.<anonymous> (/home/runner/work/vscode/vscode/actions/latest-release-monitor/index.js:12:44)

    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)

  at Module.load (node:internal/modules/cjs/loader:981:32)
15
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
16
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
17
    at node:internal/main/run_main_module:17:47
