name: Locker
on:
  schedule:
    - cron: 20 23 * * * # 4:20pm Redmond
  repository_dispatch:
    types: [trigger-locker]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          path: ./actions
          ref: v35
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Locker
        uses: ./actions/locker
        with:
          daysSinceClose: 45
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          daysSinceUpdate: 3
          ignoredLabel: "*out-of-scope"
