name: Locker
on:
  schedule:
    - cron: 20 18 * * * # 11:20am Redmond
  repository_dispatch:
    types: [trigger-locker]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: "microsoft/vscode-github-triage-actions"
          path: ./actions
          ref: stable
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Locker
        uses: ./actions/locker
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          daysSinceClose: 45
          daysSinceUpdate: 3
          ignoredLabel: "*out-of-scope,accessibility"
          ignoreLabelUntil: "author-verification-requested"
          ignoredMilestones: "Backlog Candidates"
          labelUntil: "verified"
