name: Needs More Info Labeler
on: repository_dispatch # disable pending resolution of #92958
  # issues:
  #   types: [opened, edited]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'JacksonKearl/vscode-triage-github-actions'
          ref: v11
      - name: Run Needs More Info Labeler
        uses: ./needs-more-info-labeler
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          matcher: '\b(\d\.\d{2,3}\.\d|insiders?|1\.\d\d\d?)\b'
          tags: feature_request_template
          bots: vscodebot|vscode-triage-bot
          comment: "Thanks for creating this issue! We detected it's missing some basic information, such as your VS Code and operating system versions, or in some other way doesn't follow our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines. Please take the time to review these guidelines and update the issue.\n\nThis comment will go away once sufficient information is included in your issue.\n\nHappy Coding!"
          label: needs more info
