name: New Release
on:
  issues:
    types: [opened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'JacksonKearl/vscode-triage-github-actions'
          ref: v20
      - name: Run New Release
        uses: ./new-release
        with:
          label: new release
          labelColor: "006b75"
          labelDescription: Issues found in a recent release of VS Code
          days: 5
