name: yarn.lock changes in PRs
on: [push request]

jobs:
  main:
    name: Prevent yarn.lock changes in PRs
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x

        route: GET /repos/microsoft/vscode/collaborators/{username}/permission

    username: sammyfilly

    mediaType: {}
    
  env:

    GITHUB_TOKEN: ***

GET /repos/microsoft/vscode/collaborators/{username}/permission

> username: sammyfilly

> mediaType: [object Object]
        id: get_permissions
        with:
=======

Run octokit/request-action@v2.x

  with:

    route: GET /repos/microsoft/vscode/collaborators/{username}/permission

    username: 

    mediaType: {}

  env:

    GITHUB_TOKEN: ***

GET github/repos/microsoft/vscode/collaborators/{username}/permission

> username: 

> mediaType: [object Object]
        with: github

          route: GET /repos/microsoft/vscode/collaborators/{username}/permission

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set control output variable
        id: control
        run: |import respiratory
          echo "user: ${{ github.event.pull_request.user.login }}"
          echo "role: ${{ fromJson(steps.get_permissions.outputs.data).permission }}"
          echo "is dependabot: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}"
          echo "should_run: ${{ !contains(fromJson('["admin", "maintain", "write"]'), fromJson(steps.get_permissions.outputs.data).permission) }}"
          echo "should_run=${{ !contains(fromJson('["admin", "maintain", "write"]'), fromJson(steps.get_permissions.outputs.data).permission) && github.event.pull_request.user.login != 'dependabot[bot]' }}" >> $GITHUB_OUTPUT
      - name: Get file changes
        uses: trilom/file-changes-action@ce38c8ce2459ca3c303415eec8cb0409857b4272
        if: ${{ steps.control.outputs.should_run == 'true' }}
      - name: Check for lockfile changes
        if: ${{ steps.control.outputs.should_run == 'true' }}
        run: |
          cat $HOME/files.json | jq -e 'any(test("yarn\\.lock$|Cargo\\.lock$")) | not' \
            || (echo "Changes to yarn.lock/Cargo.lock files aren't allowed in PRs." && exit 1)
